# Generated by Django 5.0.2 on 2024-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dateOfBirth', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('agender', 'Agender'), ('androgyne', 'Androgyne'), ('bigender', 'Bigender'), ('genderfluid', 'Genderfluid'), ('genderqueer', 'Genderqueer'), ('nonbinary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('cnic', models.CharField(blank=True, max_length=13, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=4, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('passportPicture1', models.ImageField(blank=True, null=True, upload_to='passport/')),
                ('cnicPicture1', models.ImageField(blank=True, null=True, upload_to='cnic/')),
                ('cnicPicture2', models.ImageField(blank=True, null=True, upload_to='cnic/')),
                ('domicilePicture', models.ImageField(blank=True, null=True, upload_to='domicile/')),
                ('farmAddress', models.TextField(blank=True, null=True)),
                ('cropsInsured', models.CharField(blank=True, choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Cotton', 'Cotton'), ('Sugarcane', 'Sugarcane'), ('Other', 'Other')], max_length=255, null=True)),
                ('otherCrop', models.CharField(blank=True, max_length=255, null=True)),
                ('acreagePlanted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cropVariety', models.CharField(blank=True, max_length=255, null=True)),
                ('plantingDate', models.CharField(blank=True, max_length=15, null=True)),
                ('selectPolicy', models.CharField(blank=True, choices=[('Ins_Crop', 'Ins Crop'), ('New_ven', 'New ven'), ('Smart_Policy', 'Smart Policy')], max_length=255, null=True)),
                ('coverageAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startDate', models.CharField(blank=True, max_length=15, null=True)),
                ('riskFactor', models.CharField(blank=True, choices=[('Floods', 'Floods'), ('Droughts', 'Droughts'), ('Hailstorms', 'Hailstorms'), ('CommonPest1', 'Pest and Disease Risks')], max_length=255, null=True)),
                ('additionalComments', models.TextField(blank=True, null=True)),
                ('paymentMethod', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=20, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=19, null=True)),
                ('cardHolderName', models.CharField(blank=True, max_length=50, null=True)),
                ('expiryDate', models.CharField(blank=True, max_length=7, null=True)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyPremiumDeductible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectPolicy', models.CharField(max_length=255, unique=True)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
