# Generated by Django 5.0.2 on 2024-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('passport_picture1', models.ImageField(blank=True, null=True, upload_to='passport/')),
                ('cnic_picture1', models.ImageField(blank=True, null=True, upload_to='cnic/')),
                ('cnic_picture2', models.ImageField(blank=True, null=True, upload_to='cnic/')),
                ('domicile_picture', models.ImageField(blank=True, null=True, upload_to='domicile/')),
                ('farm_address', models.TextField(blank=True, null=True)),
                ('crops_insured', models.TextField(blank=True, null=True)),
                ('other_crop', models.CharField(blank=True, max_length=255, null=True)),
                ('acreage_planted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crop_variety', models.CharField(blank=True, max_length=255, null=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('select_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('risk_factors', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvc', models.CharField(blank=True, max_length=4, null=True)),
                ('agree_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
