# Generated by Django 5.0.2 on 2024-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyapplication',
            name='selectPolicy',
            field=models.CharField(blank=True, choices=[('Ins_Crop', 'Ins Crop'), ('New_ven', 'New ven'), ('Smart_Policy', 'Smart Policy')], max_length=255, null=True),
        ),
    ]
