# Generated by Django 5.0.2 on 2024-05-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='premium_deductible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.policypremiumdeductible'),
        ),
        migrations.AlterField(
            model_name='policypremiumdeductible',
            name='selectPolicy',
            field=models.CharField(choices=[('Ins_Crop', 'Ins Crop'), ('New_ven', 'New ven'), ('Smart_Policy', 'Smart Policy')], max_length=255, unique=True),
        ),
    ]
