# Generated by Django 5.0.2 on 2024-05-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_policyapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyapplication',
            old_name='payment_method',
            new_name='paymentMethod',
        ),
    ]
