# Generated by Django 5.0.2 on 2024-05-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_rename_acreage_planted_policyapplication_acreageplanted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyapplication',
            name='agreeTerms',
        ),
        migrations.RemoveField(
            model_name='policyapplication',
            name='riskFactors',
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='riskFactor',
            field=models.CharField(blank=True, choices=[('Floods', 'Floods'), ('Droughts', 'Droughts'), ('Hailstorms', 'Hailstorms'), ('CommonPest1', 'Pest and Disease Risks')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='cardHolderName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='cardNumber',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='countryCode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='cropsInsured',
            field=models.CharField(blank=True, choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Cotton', 'Cotton'), ('Sugarcane', 'Sugarcane'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('agender', 'Agender'), ('androgyne', 'Androgyne'), ('bigender', 'Bigender'), ('genderfluid', 'Genderfluid'), ('genderqueer', 'Genderqueer'), ('nonbinary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='selectPolicy',
            field=models.CharField(blank=True, choices=[('policy1', 'Ins Crop'), ('policy2', 'New ven'), ('policy3', 'Smart Policy')], max_length=255, null=True),
        ),
    ]
