# Generated by Django 5.0.6 on 2024-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_policyapplication_selectpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
