# Generated by Django 5.0.6 on 2024-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.CharField(default=12, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.CharField(default=12, max_length=4),
            preserve_default=False,
        ),
    ]
