# Generated by Django 5.0.2 on 2024-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('typeOfDamage', models.CharField(choices=[('weather_related', 'Weather-related'), ('pest_related', 'Pest-related'), ('disease_related', 'Disease-related'), ('mechanical_damage', 'Mechanical damage')], max_length=20)),
                ('dateOfDamage', models.CharField(max_length=20)),
                ('extentOfDamage', models.CharField(choices=[('0-25%', '0-25% Crop Loss'), ('26-50%', '26-50% Crop Loss'), ('51-75%', '51-75% Crop Loss'), ('76-100%', '76-100% Crop Loss')], max_length=10)),
                ('witnessName', models.CharField(max_length=50)),
                ('witnessCNIC', models.CharField(max_length=13)),
                ('witnessPhoneNumber', models.CharField(max_length=20)),
                ('damageDescription', models.CharField(max_length=500)),
                ('farmerName', models.CharField(blank=True, max_length=50, null=True)),
                ('countryCode', models.CharField(choices=[('+1', '+1 (USA)'), ('+44', '+44 (UK)'), ('+92', '+92 (Pakistan)'), ('+970', '+970 (Palestine)'), ('+20', '+20 (Egypt)'), ('+962', '+962 (Jordan)'), ('+971', '+971 (UAE)')], max_length=5)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('claimPicture1', models.ImageField(blank=True, null=True, upload_to='claim_pictures/')),
                ('claimPicture2', models.ImageField(blank=True, null=True, upload_to='claim_pictures/')),
                ('claimPicture3', models.ImageField(blank=True, null=True, upload_to='claim_pictures/')),
                ('claimPicture4', models.ImageField(blank=True, null=True, upload_to='claim_pictures/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
            ],
        ),
    ]
