# Generated by Django 5.0.2 on 2024-05-15 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('insurance', '0003_policyapplication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='selectPolicy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policyapplication'),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
