# Generated by Django 5.0.2 on 2024-05-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claimapplication_selectpolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimapplication',
            old_name='status',
            new_name='claimStatus',
        ),
    ]
