# Generated by Django 5.0.2 on 2024-05-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_rename_status_claimapplication_claimstatus'),
        ('insurance', '0003_policyapplication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimapplication',
            old_name='claimStatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='claimapplication',
            name='selectPolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_applications', to='insurance.policyapplication'),
        ),
    ]
