# Generated by Django 5.0.2 on 2024-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_rename_claimstatus_claimapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimapplication',
            name='selectPolicy',
            field=models.CharField(blank=True, choices=[('Ins_Crop', 'Ins Crop'), ('New_ven', 'New ven'), ('Smart_Policy', 'Smart Policy')], max_length=255, null=True),
        ),
    ]
