# Generated by Django 5.0.2 on 2024-02-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
