# Generated by Django 5.0.2 on 2024-03-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='user',
            new_name='custom_user',
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/pictures'),
        ),
    ]
